"""empty message

Revision ID: 72494f849f9b
Revises: ed7f15060080
Create Date: 2020-10-04 14:54:02.011651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72494f849f9b'
down_revision = 'ed7f15060080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
