"""empty message

Revision ID: 9ca0c0a86acf
Revises: 47e8f54a897d
Create Date: 2020-10-04 16:01:11.409592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca0c0a86acf'
down_revision = '47e8f54a897d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
